remote_theme: pages-themes/cayman@v0.2.0
plugins: 
- jekyll-remote-theme
title: NewsOrgOnMastodon System
description: Bringing various news organizations' presence to the Mastodon network.
github:
  is_project_page: false
favicon: https://raw.githubusercontent.com/thedoggybrad/NewsOrgOnMastodonSystem/main/logo.jpeg
