remote_theme: pages-themes/cayman@v0.2.0
plugins: 
- jekyll-remote-theme
- jekyll-feed
- jekyll-seo-tag
title: NewsOrgOnMastodon System
description: Bringing various news organizations' presence to the Mastodon network.
github:
  is_project_page: false
